[toolchain]
channel = "1.85.1"
components = [
    "rustfmt",
    "clippy",
    "llvm-tools-preview",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]
profile = "minimal" 